services:
  - docker

env:
  global:
    - TERRAFORM_BUILD=terraform_build
    - AWSCLI_BUILD=awscli_build
    - TRAVIS_UID=$(id -u travis)
    - TRAVIS_GID=$(id -g travis)
    - secure: "qSmGhdh/PPMvhuJSjDyHtiOTiumjwYf46SGXMUEVJA5Jin7BOvDvI8K978DKfZZF6vwTylF6d/azEjYF11SWBBuiVWAP10gIFzNCp9I1wb+vC8XYUu/xAeQkIG7GzwvvpPyLSctDlqlKH/08pyJthvxuUU3cnFLTmbVcxN+7+Mtrtfgx4VTgynXpnjdIrjKzoEL5KoVpamSaORQ3BdxjnB9ttR0Jb9aNr4i9PM9QxoXdvr1KjAX4cf7IP28+MeIk52DKTSWcZIRjZYN/jWrWJ851O+y1XCHDxRj6m8gpRJlJWeLwu31a/73J1RwEyA/p9CxtTm8CtYz6hQPZvh1pycrQbB+X2bftYY8cnqgMkmzriNBwQw44k+r/SxadA9OqzpsJVhsqna7S9g9VdYCtz4NZSrPh90CwZP+rqKpTFVGXKojdtXR+2fKJ08liscSciCsmtY+nfag3UFoosZR/GbnAcasrgToqNJZ0qmHLeSE+sIXAS+RMGCuMHgr/4vl0LqxtVhkLst3JVv820cMCx3AbJwRdPEhB0lW+bZD5GvrSmkBAQ0oZtWFCIDs5Fneg8LznNWWPixB9+57eqdNyRWA7xlj+qfQJewCk8YuAsvp5v263b3g1ZbjWlMSh5s/pbXoax4DWEOMVSmLjUx94ku8DW+nYsojf4ITIHnvGEdo="
    - secure: "r2erkvZVtBUi8Csi9GQwgzcgfV4zfitEYDsj7puR5ApKkaTk32liCGHUcZ+88FgTNFxhAVKay2kdrJzf/3enesfrD0tXnCxX1jVhcxIbCLRENHiDNxYpFEXDhTv8UmKXu/WZDo4gF7sJeRSA6pYpCogr832YFcOll3SUbNZb27BgczyymTzNinOl7RBcIgN+FjcAqOHK7daQTMG5ov7cMP+/k9/wUfWG2PGGPlexYP5g8wVyfmXsOg1JNuSQFvzmvpcw/Mzm9PolLQdkF4BNCFYm8k5uDHf/NpoYGxkcF9Hp0lNnvYNRuYX95T2xIZMs68dd23UCCVBH99lnS/WdDGwPOLZ3SsDaB9Zb86NU+bXlvWWFeEdIM2NqSJAcDhDLc3YRS/nVWZGU/yvcCDk55UWwJdok3fuaLa+P08RddDBm5ShlZefgGqPqYHNWTEk8+IiJSXP+QVVfykKo3zUB9untSsuAuLRzSqNe5P7YrSP4DCczDOrpaGn73A3xGkv7UeWiEEJjaDFbZsKw7aPPrwbBs/rO6RTkU4vlqlYtByyYKXcRJzO1LyUOFhow65e3Ie912OmWcfluHUtI5MdZh4A/PWycSmZEzBjaCHfZQ+pTOJG2l1oke1nB9EMDiKFJM8SKkHcxpgJEBG6GCwiJOhUBVOIqqyEkB3/X3+FHkdw="

before_script:
  - git clone https://github.com/LinuxAdeptLtd/Docker-Terraform.git ${TERRAFORM_BUILD}
  - docker build -t terraform -f ${TERRAFORM_BUILD}/Dockerfile .
  - docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v $(pwd)/terraform:/data terraform init
  - docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v $(pwd)/terraform:/data terraform workspace select production
  - git clone https://github.com/LinuxAdeptLtd/Docker-awscli.git ${AWSCLI_BUILD}
  - docker build -t awscli -f ${AWSCLI_BUILD}/Dockerfile .
 
script:
  - docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v $(pwd)/terraform:/data terraform apply -auto-approve -refresh=true -var-file production.tfvars
  - docker run --rm -e JEKYLL_UID=${TRAVIS_UID} -e JEKYLL_GID=${TRAVIS_GID} -v ${PWD}/site:/srv/jekyll jekyll/jekyll jekyll build
  - docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v $(pwd)/site/_site:/data awscli s3 sync /data s3://linuxadept.io