baseURL = "http://linuxadept.io/"
languageCode = "en-us"
title = "Linux Adept"
theme = "beautifulhugo"

enableGitInfo = true
enableRobotsTXT = true

sectionPagesMenu = "main"

pygmentsCodeFences = true
pygmentsUseClasses = true
